AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
Parameters:
  ToEmail:
    Type: String
  FromEmail:
    Type: String
  IpRange:
    Type: String
Globals:
  Function:
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 15
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
  GetUrl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/GetUrl.handler
      Environment:
        Variables:
          BucketName: !Ref S3Bucket
      Events:
        GetItem:
          Type: Api
          Properties:
            Method: get
            Path: /url
            Auth:
              ResourcePolicy:
                IpRangeWhitelist:
                  - !Ref IpRange
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3Bucket
  BatteryReport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/BatteryReport.handler
      Environment:
        Variables:
          FromEmailAddress: !Ref FromEmail
          ToEmailAddress: !Ref ToEmail
      Events:
        PutItem:
          Type: Api
          Properties:
            Method: put
            Path: /battery
            Auth:
              ResourcePolicy:
                IpRangeWhitelist:
                  - !Ref IpRange
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'ses:SendEmail'
              Resource: 
                - '*'
  StateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'rekognition:DetectFaces'
                - 'rekognition:DetectLabels'
              Resource:
                - '*'
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
        - LambdaInvokePolicy:
            FunctionName: !Ref FaceDescription
        - LambdaInvokePolicy:
            FunctionName: !Ref CombineDescriptions
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'ses:SendEmail'
              Resource:
                - '*'
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'polly:StartSpeechSynthesisTask'
                - 'polly:synthesizeSpeech'
              Resource:
                - '*'
        - LambdaInvokePolicy:
            FunctionName: !Ref GetSignedImageURL
        - LambdaInvokePolicy:
            FunctionName: !Ref SynthesizeSpeech
        - LambdaInvokePolicy:
            FunctionName: !Ref SingleFaceDescription
      DefinitionUri: ./statemachine/statemachine.yaml
      DefinitionSubstitutions:
        S3Bucket: !Ref S3Bucket
        ToEmail: !Ref ToEmail
        FromEmail: !Ref FromEmail
        SynthesizeSpeech: !GetAtt SynthesizeSpeech.Arn
        FaceDescription: !GetAtt FaceDescription.Arn
        SingleFaceDescription: !GetAtt SingleFaceDescription.Arn
        CombineDescriptions: !GetAtt CombineDescriptions.Arn
        GetSignedImageURL: !GetAtt GetSignedImageURL.Arn
      Events:
        S3Event:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            InputPath: $.detail.object
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref S3Bucket
                object:
                  key:
                    - prefix: image/
  FaceDescription:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/FaceDescription.handler
      Runtime: nodejs14.x
      Timeout: 10
  SingleFaceDescription:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/SingleFaceDescription.handler
      Runtime: nodejs14.x
      Timeout: 10
  CombineDescriptions:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/CombineDescriptions.handler
      Runtime: nodejs14.x
      Timeout: 10
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
  SynthesizeSpeech:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/SynthesizeSpeech.handler
      Runtime: nodejs14.x
      Timeout: 10
      Environment:
        Variables:
          BucketName: !Ref S3Bucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'polly:SynthesizeSpeech'
              Resource:
                - '*'
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'iot:Publish'
              Resource:
                - '*'
  GetSignedImageURL:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/GetSignedImageURL.handler
      Runtime: nodejs14.x
      Timeout: 10
      Environment:
        Variables:
          BucketName: !Ref S3Bucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
